name: eviks_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.0+17

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  firebase_auth: ^4.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: any
  google_sign_in: ^6.1.0
  http: ^0.13.3
  intl: ^0.17.0
  permission_handler: ^10.2.0
  provider: ^6.0.5
  url_launcher: ^6.0.17

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.6
  flutter_svg: ^2.0.5
  image_picker: ^0.8.4+4
  flutter_staggered_animations: ^1.0.0
  skeletons: ^0.0.3
  cached_network_image: ^3.2.0
  flutter_native_splash: ^2.2.19
  firebase_messaging: ^14.5.0
  flutter_map_marker_cluster: ^1.1.0
  flutter_local_notifications: ^14.0.1
  share_plus: ^6.0.1
  photo_view: ^0.14.0
  introduction_screen: ^3.1.8

flutter_native_splash:
  color: "#BC0052"
  background_image: "assets/img/splash/splash_background.png"
  image: assets/img/splash/splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo/app_logo.png"
  adaptive_icon_background: "assets/img/logo/app_background.png"
  adaptive_icon_foreground: "assets/img/logo/app_foreground_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/illustrations/
    - assets/img/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
